import { useEffect, useState } from "react";
import { getDashboard } from "../api/adminApi";
import { EmptyState, ErrorState, LoadingState, SummaryCard } from "../components/AdminCommon";

const fmt = (value, unit = "") => value == null ? "—" : `${value}${unit}`;
export default function AdminDashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); getDashboard(controller.signal).then(([summary, gpu, users, alerts, logs]) => setData({ summary: summary.data, gpu: gpu.data, users: users.data, alerts: alerts.data, logs: logs.data })).catch((requestError) => { if (requestError.name !== "AbortError") setError(requestError.message); }); return () => controller.abort(); }, []);
  if (error) return <ErrorState message={error} />; if (!data) return <LoadingState />;
  const s = data.summary; const g = data.gpu;
  return <div className="admin-page"><section className="admin-section"><div className="admin-section-title"><div><p>서비스 현황</p><h2>운영 요약</h2></div><span>실시간 집계</span></div><div className="admin-summary-grid"><SummaryCard label="전체 사용자" value={s.total_users} /><SummaryCard label="활성 사용자" value={s.active_users} tone="good" /><SummaryCard label="비활성 사용자" value={s.inactive_users} /><SummaryCard label="오늘 가입" value={s.today_users} /><SummaryCard label="관리자" value={s.admins} /><SummaryCard label="GPU 서버" value={`${s.connected_servers}/${s.registered_servers}`} note="정상 연결 / 등록" tone={s.disconnected_servers ? "danger" : "good"} /><SummaryCard label="미확인 경고" value={s.unconfirmed_alerts} /><SummaryCard label="미처리 문의" value={s.pending_inquiries} /></div></section><section className="admin-section"><div className="admin-section-title"><div><p>기존 GPU API 집계</p><h2>GPU 요약</h2></div><span className={`admin-pill ${g.state}`}>{g.state === "success" ? "정상" : "정보 없음"}</span></div><div className="admin-summary-grid gpu-summary"><SummaryCard label="전체 GPU" value={g.total_gpus} /><SummaryCard label="평균 GPU" value={fmt(g.average_gpu_usage, "%")} /><SummaryCard label="평균 VRAM" value={fmt(g.average_memory_usage, "%")} /><SummaryCard label="평균 온도" value={fmt(g.average_temperature, "°C")} /><SummaryCard label="GPU 프로세스" value={g.process_count} /><SummaryCard label="위험 GPU" value={g.danger_gpu_count} tone={g.danger_gpu_count ? "danger" : "good"} /></div></section><div className="admin-panels"><RecentPanel title="최근 가입 사용자" rows={data.users} render={(row) => <><strong>{row.name}</strong><span>{row.email}</span><small>{new Date(row.created_at).toLocaleString("ko-KR")}</small></>} /><RecentPanel title="최근 경고" rows={data.alerts} render={() => null} /><RecentPanel title="최근 관리자 활동" rows={data.logs} render={(row) => <><strong>{row.action}</strong><span>{row.admin_name || "알 수 없음"}</span><small>{new Date(row.created_at).toLocaleString("ko-KR")}</small></>} /></div></div>;
}
function RecentPanel({ title, rows, render }) { return <section className="admin-panel"><h2>{title}</h2>{rows.length ? <ul>{rows.map((row) => <li key={row.id}>{render(row)}</li>)}</ul> : <EmptyState />}</section>; }
