import { useEffect, useState } from "react";
import { getAdminUsers } from "../api/adminApi";
import { EmptyState, ErrorState, LoadingState, Pagination } from "../components/AdminCommon";

export default function UserManagementPage() {
  const [query, setQuery] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [result, setResult] = useState(null); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); getAdminUsers({ page, size: 20, search, sort: "created_at", order: "desc" }, controller.signal).then((response) => { setResult(response.data); setError(""); }).catch((requestError) => { if (requestError.name !== "AbortError") setError(requestError.message); }); return () => controller.abort(); }, [page, search]);
  return <div className="admin-page"><section className="admin-section"><div className="admin-section-title"><div><p>MEMBERS</p><h2>사용자 목록</h2></div><span>{result?.total ?? 0}명</span></div><form className="admin-filter" onSubmit={(event) => { event.preventDefault(); setPage(1); setSearch(query); }}><label htmlFor="user-search">이름, 닉네임, 이메일 또는 ID 검색</label><div><input id="user-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="검색어 입력" /><button className="admin-primary">검색</button></div></form>{error ? <ErrorState message={error} /> : !result ? <LoadingState /> : result.items.length === 0 ? <EmptyState message={search ? "검색 결과가 없습니다." : undefined} /> : <div className="admin-table-wrap"><table><thead><tr><th>ID</th><th>사용자</th><th>닉네임</th><th>이메일</th><th>권한</th><th>상태</th><th>가입일</th><th>마지막 로그인</th></tr></thead><tbody>{result.items.map((user) => <tr key={user.id}><td>#{user.id}</td><td><div className="user-cell"><span aria-hidden="true">{user.name.slice(0, 1)}</span><strong>{user.name}</strong></div></td><td>{user.nickname || "—"}</td><td>{user.email}</td><td><span className="admin-pill">{user.role}</span></td><td><span className={`admin-pill ${user.status === "ACTIVE" ? "success" : "unavailable"}`}>{user.status}</span></td><td>{new Date(user.created_at).toLocaleDateString("ko-KR")}</td><td>{user.last_login_at ? new Date(user.last_login_at).toLocaleString("ko-KR") : "—"}</td></tr>)}</tbody></table></div>}<Pagination page={page} totalPages={result?.total_pages || 0} onChange={setPage} /></section></div>;
}
