apiVersion: v1
kind: Secret
metadata:
  name: cineverse-secrets
  namespace: cineverse
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://USER:PASSWORD@db.internal:6432/CineVerse
  SECRET_KEY: REPLACE_WITH_LONG_RANDOM_VALUE
  TMDB_ACCESS_TOKEN: REPLACE_WITH_TMDB_ACCESS_TOKEN
  MAIL_USERNAME: REPLACE_WITH_SMTP_USERNAME
  MAIL_PASSWORD: REPLACE_WITH_SMTP_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: cineverse-migration-secrets
  namespace: cineverse
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://USER:PASSWORD@db.internal:5432/CineVerse
  SECRET_KEY: REPLACE_WITH_LONG_RANDOM_VALUE
  TMDB_ACCESS_TOKEN: REPLACE_WITH_TMDB_ACCESS_TOKEN
  MAIL_USERNAME: REPLACE_WITH_SMTP_USERNAME
  MAIL_PASSWORD: REPLACE_WITH_SMTP_PASSWORD
