apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  namespace: cineverse
spec:
  storageClassName: REPLACE_ME_RWX_STORAGE_CLASS
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: REPLACE_ME_STORAGE_SIZE
