apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: cineverse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: cineverse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
