export const KEYWORD_LABELS = {
  'based on novel or book': '소설·책 원작',
  'based on true story': '실화 바탕',
  revenge: '복수',
  friendship: '우정',
  love: '사랑',
  'coming of age': '성장',
  family: '가족',
  detective: '탐정·추리',
  superhero: '슈퍼히어로',
  dystopia: '디스토피아',
  supernatural: '초자연',
  magic: '마법',
  'time travel': '시간 여행',
  survival: '생존',
  'road trip': '로드 트립',
  sports: '스포츠',
  'martial arts': '무술',
  alien: '외계 생명체',
  'alien invasion': '외계 침공',
  'dark comedy': '블랙 코미디',
  animation: '애니메이션',
  'based on webcomic or webtoon': '웹툰 원작',
  cooking: '요리',
  food: '요리',
  'magazine editor': '잡지 편집자',
  musical: '뮤지컬',
  'body exchange': '몸 바꾸기',
  bromance: '브로맨스',
  advertising: '광고',
  romcom: '로맨틱 코미디',
  remake: '리메이크',
  castle: '성',
  transformation: '변신',
  cartoon: '만화',
  france: '프랑스',
  'fairy tale': '동화',
  'new york city': '뉴욕',
  hero: '영웅',
  'based on young adult novel': '청소년 소설 원작',
  zombie: '좀비',
  'post-apocalyptic future': '포스트 아포칼립스',
  'interspecies romance': '종족을 초월한 사랑',
  'zombie apocalypse': '좀비 아포칼립스',
  romance: '로맨스',
  satire: '풍자',
  '20th century': '20세기',
  'fight for survival': '생존 투쟁',
  'police chief': '경찰서장',
  aliens: '외계 생명체',
  'remote village': '외딴 마을',
  hunted: '추격',
  'police officer': '경찰관',
  'gwangju uprising': '광주 민주화 운동',
  democracy: '민주주의',
  'political conspiracy': '정치적 음모',
  'undercover operation': '잠입 작전',
  taxi: '택시',
  '1980s': '1980년대',
  'double cross': '배신',
  'historical event': '역사적 사건',
  'inter-korean relations': '남북 관계',
  'double agent': '이중 스파이',
  'taxi driver': '택시 기사',
  'north korea': '북한',
  protest: '시위',
  'south korea': '대한민국',
  'national intelligence service (nis)': '국가정보원',
  'teenage crush': '십 대의 짝사랑',
  'bad boy': '나쁜 남자',
  'teenage girl': '십 대 소녀',
  'teenage romance': '십 대 로맨스',
  angry: '분노',
  mysterious: '미스터리',
  spoof: '패러디',
  'alternative present': '대체 현실',
  'low self esteem': '낮은 자존감',
  parody: '패러디',
  witch: '마녀',
  'parent child relationship': '부모와 자녀 관계',
  'abusive father': '폭력적인 아버지',
  pacifism: '평화주의',
  'world war ii': '제2차 세계대전',
  bible: '성경',
  vegetarian: '채식주의자',
  japan: '일본',
  gore: '고어',
  'based on play or musical': '연극·뮤지컬 원작',
  'single mother': '싱글맘',
  'unknown father': '아버지의 부재',
  'single parent': '한부모 가정',
  greece: '그리스',
  'family holiday': '가족 여행',
  'artificial intelligence (a.i.)': '인공지능',
  computer: '컴퓨터',
  'virtual reality': '가상현실',
  'adult animation': '성인 애니메이션',
  'card game': '카드 게임',
  cybercrime: '사이버 범죄',
  hacker: '해커',
  'world cup': '월드컵',
  mermaid: '인어',
  'boarding school': '기숙학교',
  'dying and death': '죽음',
  maze: '미로',
  'secret identity': '숨겨진 정체',
  'based on comic': '만화 원작',
  villain: '악당',
  sequel: '속편',
  'marvel cinematic universe (mcu)': '마블 시네마틱 유니버스',
  corruption: '부패',
  ambition: '야망',
  aftercreditsstinger: '쿠키 영상',
  'short film': '단편 영화',
  'family secrets': '가족의 비밀',
  'sibling relationship': '형제자매 관계',
  'mind control': '정신 조종',
  escape: '탈출',
  freedom: '자유',
  hope: '희망',
  'loss of loved one': '상실',
  melancholy: '쓸쓸한 분위기',
  mutation: '돌연변이',
  prison: '감옥',
  dance: '춤',
  'high school': '고등학교',
  jazz: '재즈',
};

export function getKeywordLabel(keyword, { compact = false, hashtag = false } = {}) {
  const normalized = String(keyword ?? '').trim();
  if (!normalized) return '';
  const label = KEYWORD_LABELS[normalized.toLocaleLowerCase('en-US')] || normalized;
  const displayed = compact ? label.replace(/\s+/g, '') : label;
  return hashtag ? `#${displayed}` : displayed;
}
